### ISSUE TITLE
After EP update, taskbar buttons always shows full (long) title 

### ISSUE THREAD

**Issue by kleinerSpinner** [valinet/ExplorerPatcher#1192]
This was not the case before the update.
Now it seems this can't be changed, neither via properties (ES), nor via settings (Windows)?!

**Comment by kleinerSpinner** [comment]
Hm.
Was there another update, or did the two Windows restarts I had to go through change the behaviour?
For the moment, it seems that the issue is resolved and the behaviour is back to how it was before...

**Comment by tommysolinas** [comment]
For me is still a problem.. you just had to restart Windows to make it work as intended?

**Comment by blueputty01** [comment]
@kleinerSpinner @tommysolinas Are the settings below not functioning on your machine? Sometimes, the "Restart File Explorer" link at the bottom left of the properties panel can alleviate the issue without a full system restart.

![image](https://user-images.githubusercontent.com/65861156/227645417-d48c9463-62e2-4426-899b-d4ab4d672e69.png)

**Comment by tommysolinas** [comment]
Oh, I think initially I didn't have them, when I first used it!
Now everything works perfectly fine, thank you!
