### ISSUE TITLE
Weather is not displayed

### ISSUE THREAD

**Issue by stardepp** [valinet/ExplorerPatcher#1324]
The weather is not displayed, error visible, see gif:  https://imgur.com/34EXFFI   https://imgur.com/7Jzxoby

Edition	Windows 11 Pro
Version	22H2
Betriebssystembuild	22621.1555

**Comment by gitanO0** [comment]
Same issue for me as well.

**Comment by anonymous3123** [comment]
Same issue here

**Comment by RolandYip** [comment]
same issude here
win ver 22h2

**Comment by rodrigoma-zz** [comment]
Same issue here

**Comment by felikjunvianto** [comment]
Rolling back seems to fix the issue. See here: https://github.com/valinet/ExplorerPatcher/issues/1310

**Comment by stardepp** [comment]
@felikjunvianto Thanks for this tip, yes this works so well.

**Comment by edzucker** [comment]
Same issue here. Windows 11 Pro 22H2 22621.1555

**Comment by SamBukka** [comment]
You can use 22621.1413.54.5 with the old "ep_weather_host.dll" from 22621.1344.53.1.

Just disable weather, replace the dll in "c:\Program Files\ExplorerPatcher\" and re-enable weather.

here is the dll: https://rg.to/file/d9ba10fc3f7640f1451ee5a1588204b7/ep_weather_host.dll.html

**Comment by Diego02upa** [comment]
> You can use 22621.1413.54.5 with the old "ep_weather_host.dll" from 22621.1344.53.1.
> 
> Just disable weather, replace the dll in "c:\Program Files\ExplorerPatcher" and re-enable weather.
> 
> here is the dll: https://rg.to/file/d9ba10fc3f7640f1451ee5a1588204b7/ep_weather_host.dll.html

YES, WORK!! Thank

But the weather icons in the weather screen are different from the one you see directly in the taskbar: why? Those that you see directly in the taskbar are more elegant. Can it be fixed? Thank you so much.

**Comment by hei-sch** [comment]
Re: SamBukka - Hi SamBukka, thanks for your workaround, it works great.

**Comment by o-JOHN-o** [comment]
Aye, it be the same over here too.

**Comment by valinet** [comment]
Latest version (22621.1555.55.1) should fix this issue.

**Comment by markusb68** [comment]
This issue came back:
![image](https://github.com/valinet/ExplorerPatcher/assets/20417704/63adecad-24f3-4cec-9ee7-5b7eb25e868b)
![image](https://github.com/valinet/ExplorerPatcher/assets/20417704/42f81674-be99-4f08-9c3a-ff11f48156ba)
![image](https://github.com/valinet/ExplorerPatcher/assets/20417704/304eaba7-0a1b-4481-9b73-0a10f1c23d25)
![image](https://github.com/valinet/ExplorerPatcher/assets/20417704/7cd9ef41-01b2-4091-a201-13ee793381b3)

**Comment by stardepp** [comment]
@markusb68 Yes, I can confirm that. You can reactivate the weather by clicking on "Show weather on the taskbar" even if the checkmark is set.

**Comment by markusb68** [comment]
Sorry, reactivating the weather by clicking on "Show weather on the taskbar" didn't help. 
It pretends there is no internet:
![image](https://github.com/valinet/ExplorerPatcher/assets/20417704/54c3d98b-e364-4e4d-85ad-bfa5333d6a96)

Looks to me that Google wants to get some EULA accepted:
![image](https://github.com/valinet/ExplorerPatcher/assets/20417704/ce81086d-dfb5-4a93-a254-592e206ac65d)

**Comment by markusb68** [comment]
I have maximized the window.
Then clicked reload.
Then the google message appears:
![image](https://github.com/valinet/ExplorerPatcher/assets/20417704/e690c94b-6241-4474-ba13-ebdfc03e9cb7)

But before I can scroll down and click accept the windows shrinks again:
![image](https://github.com/valinet/ExplorerPatcher/assets/20417704/5b387a26-6f59-452c-b02e-de2ae67f5f9f)

So I can't get any ID out of it.

**Comment by markusb68** [comment]
Update: Now it works again. I did nothing. Maybe it was a problem caused by Google.
Anyway thanks for your support and effort !
