### ISSUE TITLE
[Windows 11] unable to maintain internet connection

### ISSUE THREAD

**Issue by tambow44** [valinet/ExplorerPatcher#1334]
Can't see of the Windows security settings blocking this tool from internet access, and can see it does fetch some data initially.

As illustrated:

![weather-issue](https://user-images.githubusercontent.com/29732094/232308285-ab4babdb-99d4-47d1-a2d7-f314b7cc35d7.gif)

**Comment by topia** [comment]
https://github.com/valinet/ExplorerPatcher/issues/1310#issuecomment-1507923790

**Comment by hei-sch** [comment]
Re: SamBukka - Hi SamBukka, thanks for your workaround, it works great.

**Comment by E-S-F** [comment]
Thx, SamBukka.

**Comment by cjahn50** [comment]
Just ran into this today though this is not the first time this has happened. I would assume is a Google issue. It was working fine yesterday, and nothing has changed on the PC. Stopping and restarting does not make a difference and has been mentioned, the old .dll is not available any more.

**Comment by icebluSky25** [comment]
Same issue for me. 

I'd love to try replacing the .dll if someone would post it for download.

For me, EP seemed to break after the latest Windows update, but maybe that was just coincidence.

After the update troubles I uninstalled EP and tried to live without it, but I really like it, especially the weather widget, so I reinstalled the latest release.

It all works great now, except the weather widget.

Same problem as the video above and others are reporting:
    Unable to Load message
    
Clicking the re-load link in the message box causes it to flash a 1-sec view of the correct weather info (it even has the temp in Celsius, and the name of my small town specified in settings), but then immediately reverts to: Unable to Load message.

Any posted .dll solution, advice, or suggestions, would be appreciated

**Comment by cjahn50** [comment]
FYI... I tried the old ep_weather_host.dll and there was no change. The widget will display a condensed version of the weather for a while, then stop updating and complain about the network connection. This has got to be a Google issue.

I had stashed a copy of the old .dll back when that actually worked. Could not find it today doing a search.

**Comment by MickeyM007** [comment]
Yes, it is a cookie content window from Google that prevent the weather widget to load. Ones in a while this will happen. If you click on "Reload". You'll see it for a second. If it stays longer than 1 second, you may be able to "accept" with TAB and <enter>. But the message: "Could not load weather information" will appear after a second again.

**Comment by pyrates999** [comment]
What we need to know is if the `Unable to load weather information with the reload button` is from EP or from google's weather website.

**Comment by AzureWoof** [comment]
Hi, new user of ExplorerPatcher here. I'm getting this issue too.

**Comment by ffscz** [comment]
same issue here

**Comment by cjahn50** [comment]
> What we need to know is if the `Unable to load weather information with the reload button` is from EP or from Google's weather website.

This doesn't appear to be related to EP if only because it worked just fine until yesterday.  I'm on EP version 22631.5335.68.2 (the latest) and like I said, the widget was working from when I did the update 3 weeks ago until yesterday 6/8.

**Comment by MickeyM007** [comment]
This happens occasionally. Previously, the widget would not load because of Google's cookie notification. Then, I could "reload" and use the keyboard (TAB, TAB+space/Enter) to select "Accept All" or "Reject All" to solve the problem. But now it does not work anymore:

<img width="455" alt="Image" src="https://github.com/user-attachments/assets/2498a0a1-01bf-4161-a9c1-475cd1e8653a" />

It also reads:  "Results for.." 
<img width="455" alt="Image" src="https://github.com/user-attachments/assets/d27c8079-4087-4309-849a-c977d1ffb5c0" />

I managed to accept the cookies (clear local data from the weather widget -> clicked "^" on the taskbar (to open the hidden icons) -> clicked on the weather widget icon -> clicked "reload" -> select the text in the cookie notification -> 4x TAB -> space bar).
<img width="454" alt="Image" src="https://github.com/user-attachments/assets/d91221f0-d42b-4eda-8514-a9207fe74bf2" />

Now the cookie consent window is gone. "Unable to load weather information" shows up again. When I clicked "reload", I see the weather info without the cookie window. But now I can scroll for a second in that widget window with the mouse wheel (before, when the widget worked, I couldn't). When I scroll down, it looks like Google Search:
<img width="454" alt="Image" src="https://github.com/user-attachments/assets/2ac6e196-f145-4127-87b1-bb94a5708f1f" />

**Comment by lucvw1975** [comment]
Same problem. Started today, but the issue could have started earlier because I was a few days away from my pc. I also had problems with Youtube, so maybe it's Google related as some people say. Anyway, I hope there's a solution for this, because I really like the ExplorerPatcher and its weather widget. Thanks ! :)

**Comment by drezprime** [comment]
> This happens occasionally. Previously, the widget would not load because of Google's cookie notification. Then, I could "reload" and use the keyboard (TAB, TAB+space/Enter) to select "Accept All" or "Reject All" to solve the problem. But now it does not work anymore:
> 
> <img alt="Image" width="455" src="https://private-user-images.githubusercontent.com/114982418/453114408-2498a0a1-01bf-4161-a9c1-475cd1e8653a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk1Mjg2NTQsIm5iZiI6MTc0OTUyODM1NCwicGF0aCI6Ii8xMTQ5ODI0MTgvNDUzMTE0NDA4LTI0OThhMGExLTAxYmYtNDE2MS1hOWMxLTQ3NWNkMWU4NjUzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxMFQwNDA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTI2MTE1YTgwNjcxZjk2Yzg3MjNmZjBmNDgzNjIyNDg1OGYwZjVlMjA2ODhlOTBmMmY3ZjVhNjMyYzU3NjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8zBgX_A06eqHvknfC4-290j3c-Ij9aV8n-y-JkU2BxQ">
> It also reads: "Results for.." <img alt="Image" width="455" src="https://private-user-images.githubusercontent.com/114982418/453114544-d27c8079-4087-4309-849a-c977d1ffb5c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk1Mjg2NTQsIm5iZiI6MTc0OTUyODM1NCwicGF0aCI6Ii8xMTQ5ODI0MTgvNDUzMTE0NTQ0LWQyN2M4MDc5LTQwODctNDMwOS04NDlhLWM5NzdkMWZmYjVjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxMFQwNDA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmMzMTNkMTUzMTQ0OGQyNjk1YzU2ZDU5ZjQ2YmEzZDNkMWFiMDEyY2NmOGIzYmY1ZmFhNzcwNjM3ODYxNTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wWs0pw8TUerJLgwcIZQODs4BSZrv2oWa_2Nae-lGk6A">
> 
> I managed to accept the cookies (clear local data from the weather widget -> clicked "^" on the taskbar (to open the hidden icons) -> clicked on the weather widget icon -> clicked "reload" -> select the text in the cookie notification -> 4x TAB -> space bar). <img alt="Image" width="454" src="https://private-user-images.githubusercontent.com/114982418/453114618-d91221f0-d42b-4eda-8514-a9207fe74bf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk1Mjg2NTQsIm5iZiI6MTc0OTUyODM1NCwicGF0aCI6Ii8xMTQ5ODI0MTgvNDUzMTE0NjE4LWQ5MTIyMWYwLWQ0MmItNGVkYS04NTE0LWE5MjA3ZmU3NGJmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxMFQwNDA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjg4MGEyZmE5ODkyNDM1YjI0OGZjYjM5NTZjZTgyZTViZDk4MjczNzY5ZDM4MjAwOTJjMzU1ZmUwOGYxNjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lFGp60h_dkP6uENTRMSjNA0jw1zP2C3qRIXxqAyDZgs">
> 
> Now the cookie consent window is gone. "Unable to load weather information" shows up again. When I clicked "reload", I see the weather info without the cookie window. But now I can scroll for a second in that widget window with the mouse wheel (before, when the widget worked, I couldn't). When I scroll down, it looks like Google Search: <img alt="Image" width="454" src="https://private-user-images.githubusercontent.com/114982418/453114707-2ac6e196-f145-4127-87b1-bb94a5708f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk1Mjg2NTQsIm5iZiI6MTc0OTUyODM1NCwicGF0aCI6Ii8xMTQ5ODI0MTgvNDUzMTE0NzA3LTJhYzZlMTk2LWYxNDUtNDEyNy04N2IxLWJiOTRhNTcwOGYxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxMFQwNDA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjBkOWIzMWY2MTc4MGE1ZWViOWVkZmQwZWQ4NDljYzZiZjg5MjU1MGJkMzM5NDM1NmMyM2I1NzY2NjQ0M2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5hQQmyd7soSIcAYgPm32qkWMHZkLe2MGAOBV8S5b0KM">

look, he lied again! him and his boy want the new thread closed when this one, after 3 years, STILL ISNT FIXED,  You and pyrateasslube need to shut the fuck up unless you are getting the devs here money and by the looks of your history you just piss and moan even on reddit.  shut the fuck up, you cant help, let the devs work on it, got me there tiger?

**Comment by MickeyM007** [comment]
@drezprime It was fixed before. This is a new problem: It seems that Google recently changed some things, that caused the weather widget to stop working. I mean it always worked, no? 

Not sure what your problem is (rhetorical). I'm not lying: These are screenshots I made yesterday. Maybe they'll help to pinpoint the problem). Also, I'm not on Reddit.

**Comment by drezprime** [comment]
i hope when the devs see this pissing in the wind thread that they either STOP development or ban everyone

**Comment by drezprime** [comment]
@MickeyM007 look you and your boy @pyrates999 who wont let things go and want a new thread closed for a 4 year old thread to be reopened when neither of you pay or donate to development.  I know I don't, and thats fine, with the way you wtwo assholes act to people I'd stop public dev and make it pure paid private.  and dont give me the you dont know whats up my ass problem, go look at the threads with you and your butt buddy and figure it out.   All we wanted was weather, @pyrates999 say to go fuck ourselves and to close the thread since one from FOUR YEARS was posted. (wtf?  is he a fucking retarded mongaloid saying that?)
Unless people are going to donate I wish the devs well and hope they close this github because of you two.

**Comment by GitTomTom** [comment]
Same issue here from a relatively new user, 
Mt Details: Windows 11, build 22631.5413; ExplorerPatcher 22631.5335.68.2; OpenShell 4.4.196; Windows Defender and NordVPN. Added exclusions to WD, tried replacing the weather DLLs, disabled VPN, etc. Nothing worked, BUT...
This is a fantastic project even without the weather and I donated today. I regret the ugly comments that many have posted and hope you respect the developer(s) as well as your fellow commenters...and DONATE if you haven't already. Also, for those who may be coders, I'm fairly sure that constructive help would be appreciated!

**Comment by gtdurham** [comment]
I was able to download 22621.1413.54.5 but when I tried this "ep_weather_host.dll" from 22621.1344.53.1 and replace it with the old "ep_weather_host.dll", it still didn't work. I believe this issue is related to 24H2 because it still works on 23H2.

**Comment by cjahn50** [comment]
I mentioned in an earlier post that the old .dll from 53.1 did not work. And FWIW - This has been working just fine since I updated to 24H2 when it came out. So if this is indeed related to 24H2, it is a change the Google recently made that's got the issue with 24H2.

**Comment by dissonator** [comment]
W11 23H2 22631.3155 & EP 22631.5335.68.2 same problem since yesterday. All works perfectly exception weather widget ((( 
"Unable to load weather information
Make sure that the location you have entered is correct.
Verify that you are connected to the Internet."
Reload from widget window and from ep window doesn't change the situation. Trick with cookie accept don't work. Rollback ep_weather_host.dll version to 22621.1344.53.1 useless.
Please fix it. Weather widget is real killer feauture! Thx

**2025-06-12 6:25PM GMT+3 update:** The problem resolved itself. The widget is working properly again. Apparently, there were issues on Google's or Microsoft's side.

**Comment by pyrates999** [comment]
I just thought of something.  For those where this is not working:

open up chrome and put the following: `weather location`
replace `location` with the value you are putting in EP for the weather

for example if the location is `los angeles, california`: `weather los angeles, california`

and show a screen shot of what you are getting.

**Comment by cjahn50** [comment]
> I just thought of something. For those where this is not working:
> 
> open up chrome and put the following: `weather location` replace `location` with the value you are putting in EP for the weather
> 
> for example if the location is `los angeles, california`: `weather los angeles, california`
> 
> and show a screen shot of what you are getting.

I see the same thing in Chrome as I do/did in Edge. I went to Chrome/Google and did as you suggested when this started. It is not the same graphic as seen in EP, but here you go.

![Image](https://github.com/user-attachments/assets/eecbef38-5c9f-4130-9c6b-0f72c3caba55)

**Comment by d0ct0rd00m** [comment]
> W11 23H2 22631.3155 & EP 22631.5335.68.2 same problem since yesterday. All works perfectly exception weather widget ((( "Unable to load weather information Make sure that the location you have entered is correct. Verify that you are connected to the Internet." Reload from widget window and from ep window doesn't change the situation. Trick with cookie accept don't work. Rollback ep_weather_host.dll version to 22621.1344.53.1 useless. Please fix it. Weather widget is real killer feauture! Thx
> 
> **2025-06-12 6:25PM GMT+3 update:** The problem resolved itself. The widget is working properly again. Apparently, there were issues on Google's or Microsoft's side.

I went to clear the weather data and its still broken.

**Comment by dissonator** [comment]
> > **2025-06-12 6:25PM GMT+3 update:** The problem resolved itself. The widget is working properly again. Apparently, there were issues on Google's or Microsoft's side.

> I went to clear the weather data and its still broken.

After the "Clear weather widget local data", it stopped working again. More than strange behavior. I continue to observe lol..

**Comment by cjahn50** [comment]
Clearing the widget data will blow it up after the workaround. You'll have to apply the workaround again to get it back. And, FWIW, I updated Win11 today and with today's changes, the behavior of EP weather did not change. 

All that said, unless you need to clear the widgets data, the workaround is pretty solid.

**Comment by pyrates999** [comment]
> > I just thought of something. For those where this is not working:
> > open up chrome and put the following: `weather location` replace `location` with the value you are putting in EP for the weather
> > for example if the location is `los angeles, california`: `weather los angeles, california`
> > and show a screen shot of what you are getting.
> 
> I see the same thing in Chrome as I do/did in Edge. I went to Chrome/Google and did as you suggested when this started. It is not the same graphic as seen in EP, but here you go.
> 
> ![Image](https://github.com/user-attachments/assets/eecbef38-5c9f-4130-9c6b-0f72c3caba55)

Then something in the html being returned is causing EP to think the weather data is not in the format it is expecting, thus it may show that unable to load weather information.

**Comment by davids5** [comment]
> Clearing the widget data will blow it up after the workaround. You'll have to apply the workaround again to get it back. And, FWIW, I updated Win11 today and with today's changes, the behavior of EP weather did not change.
> 
> All that said, unless you need to clear the widgets data, the workaround is pretty solid.

What Workaround are you referring to?

**Comment by cjahn50** [comment]
> > Clearing the widget data will blow it up after the workaround. You'll have to apply the workaround again to get it back. And, FWIW, I updated Win11 today and with today's changes, the behavior of EP weather did not change.
> > All that said, unless you need to clear the widgets data, the workaround is pretty solid.
> 
> What Workaround are you referring to?

See this thread - https://github.com/valinet/ExplorerPatcher/issues/4351.

Scroll down and check out this post from bbmaster123 - [bbmaster123](https://github.com/bbmaster123)
[2 days ago](https://github.com/valinet/ExplorerPatcher/issues/4351#issuecomment-2964378864) · edited by [bbmaster123](https://github.com/bbmaster123)

**Comment by ChuckIn85085** [comment]
> You can use 22621.1413.54.5 with the old "ep_weather_host.dll" from 22621.1344.53.1.
> 
> Just disable weather, replace the dll in "c:\Program Files\ExplorerPatcher" and re-enable weather.
> 
> here is the dll: https://rg.to/file/d9ba10fc3f7640f1451ee5a1588204b7/ep_weather_host.dll.html

This file is no longer available. Can you please post a link to the DLL file you would like everyone who is experiencing the problem to use?

Thanks!

**Comment by dissonator** [comment]
> Can you please post a link to the DLL file you would like everyone who is experiencing the problem to use?

[https://www.upload.ee/files/18216952/ep_weather_host.dll.html](url)
Unfortunately, this trick didn't work for me.

**Comment by ChuckIn85085** [comment]
> > Can you please post a link to the DLL file you would like everyone who is experiencing the problem to use?
> 
> [https://www.upload.ee/files/18216952/ep_weather_host.dll.html](url) Unfortunately, this trick didn't work for me.

Yip! Doesn't work for me here either.

Guess we no longer have the weather widget available to us...

**Comment by dissonator** [comment]
> Guess we no longer have the weather widget available to us...

Not everything is lost. It's a bit clumsy, but I still managed to get the widget working on my W11 23H2 3155. I will describe my actions later, after some experiments.

![Image](https://github.com/user-attachments/assets/3e35a31a-cbd5-4069-b2d9-525a7fc06f55)

**Comment by pyrates999** [comment]
If you're gonna try a previous version of ep_weather_host.dll, go here and extract each previous release to get the file you're looking for: https://github.com/valinet/ExplorerPatcher/releases

see here for how to extract it: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To#how-to-obtain-explorerpatchers-files-without-installing-it-on-the-machine

**Comment by lucvw1975** [comment]
Just wanted to let you know that the weather widget magically started working again today. I don't know what's changed, only that I updated my Chrome to the latest version. Although I doubt this has anything to do with it. Anyway, glad things work again, I hope it'll stay this way and also that it starts working for everyone again :)

**Comment by dissonator** [comment]
> Just wanted to let you know that the weather widget magically started working again today. 

https://github.com/valinet/ExplorerPatcher/issues/1334#issuecomment-2962160875 see **update**
Stops working after "Clear weather widget local data"... It's not worth doing that lol

**Comment by mmalloy0** [comment]
@dissonator my weather widget is still not working. Attempted to extract and use the ep_weather_host.dll file from some earlier versions and also rolling back to an earlier EP version, no go and not fixed after this. Thoughts?

**Comment by davids5** [comment]
see https://github.com/valinet/ExplorerPatcher/issues/4351#issuecomment-2990507603 for a working DLL

**Comment by pyrates999** [comment]
If it is dynamic, that means your patch will not work.  Let me know if I'm wrong though.

**Comment by Galthariel** [comment]
> see [#4351 (comment)](https://github.com/valinet/ExplorerPatcher/issues/4351#issuecomment-2990507603) for a working DLL

This new DLL worked flawless. Not even need to clear widget local data but to make sure it was working I did clear and like I said...it's working. Tks a lot for pointing out the solution. No Explorer or Computer restart was needed.

**Comment by cjahn50** [comment]
So what I found using the patched .dll. The display is the old display AND you can scroll it just like the webpage it is. But the Precipitation and Wind toggles did not work. And, once you do the infamous Clear weather widget local data it blows up. So far the only "workaround" that works for me is using the Local State file from my Edge directory.  That allows the widget to behave like it should (it can't be scrolled and the Temperature, Precipitation and Wind toggles all work). BUT, clearing the local data will blow it up.

**Comment by ChuckIn85085** [comment]
Have used this for a couple days on a couple machines. What I have found is this on my daily machine:

After turning the weather widget OFF and replacing the dll with the one supplied in this thread, the display looks just as it used to:

![Image](https://github.com/user-attachments/assets/4ddc9d68-a44a-4894-80aa-12309c165d1d)

However, when clicking on the weather info on the taskbar, nothing is clickable (Temp, Wind, Precipitation, More Info, etc.) on the popup window:

![Image](https://github.com/user-attachments/assets/5cb2cb53-11f7-426a-be0c-6b6300aa979f)

So, in turn, it's just a static display with no functioning links.

At least it's a weather display that functions better than ExplorerPatcher was last week.

**Comment by Galthariel** [comment]
> Have used this for a couple days on a couple machines. What I have found is this on my daily machine:
> 
> After turning the weather widget OFF and replacing the dll with the one supplied in this thread, the display looks just as it used to:
> 
> ![Image](https://github.com/user-attachments/assets/4ddc9d68-a44a-4894-80aa-12309c165d1d)
> 
> However, when clicking on the weather info on the taskbar, nothing is clickable (Temp, Wind, Precipitation, More Info, etc.) on the popup window:
> 
> ![Image](https://github.com/user-attachments/assets/5cb2cb53-11f7-426a-be0c-6b6300aa979f)
> 
> So, in turn, it's just a static display with no functioning links.
> 
> At least it's a weather display that functions better than ExplorerPatcher was last week.

On mine, everything is clickable and usable. Have you tried to Clear Weather Widget Data? I'm on 24H2 - 26100.4351

**Comment by ChuckIn85085** [comment]
> On mine, everything is clickable and usable. Have you tried to Clear Weather Widget Data? I'm on 24H2 - 26100.4351

Absolutely! I always try TShooting as much as possible before posting...

https://github.com/user-attachments/assets/4f0518d9-2e7f-42fb-b58b-e08dc99dbcef

Win11 Pro:

![Image](https://github.com/user-attachments/assets/01ae6586-0834-4b40-bd0e-2ad256047926)

![Image](https://github.com/user-attachments/assets/f8b8439e-f563-48e3-9526-aa143cb4bcef)

**Comment by cjahn50** [comment]
> > On mine, everything is clickable and usable. Have you tried to Clear Weather Widget Data? I'm on 24H2 - 26100.4351
> 
> Absolutely! I always try TShooting as much as possible before posting...
> 
>  EPatcher.mp4 
> Win11 Pro:
> 
> ![Image](https://github.com/user-attachments/assets/01ae6586-0834-4b40-bd0e-2ad256047926)
> 
> ![Image](https://github.com/user-attachments/assets/f8b8439e-f563-48e3-9526-aa143cb4bcef)

I ran into the same results. I posted this yesterday:

So what I found using the patched .dll. The display is the old display AND you can scroll it just like the webpage it is. But the Precipitation and Wind toggles did not work. And, once you do the infamous Clear weather widget local data it blows up. So far the only "workaround" that works for me is using the Local State file from my Edge directory. That allows the widget to behave like it should (it can't be scrolled and the Temperature, Precipitation and Wind toggles all work). BUT, clearing the local data will blow it up.

Same version of Windows 11 and EP version 68.2.

**Comment by ChuckIn85085** [comment]
> I ran into the same results. I posted this yesterday:
> 
> So what I found using the patched .dll. The display is the old display AND you can scroll it just like the webpage it is. But the Precipitation and Wind toggles did not work. And, once you do the infamous Clear weather widget local data it blows up. So far the only "workaround" that works for me is using the Local State file from my Edge directory. That allows the widget to behave like it should (it can't be scrolled and the Temperature, Precipitation and Wind toggles all work). BUT, clearing the local data will blow it up.
> 
> Same version of Windows 11 and EP version 68.2.

Now see for me, I can clear the weather data the 1st time and it blew up. After about 30 seconds, the weather data came back with no issue. Now when I do either clear weather data, or update weather data, I get a success message with no issue.

Just can't click anything. But like I said, at least the weather is back. ;-)

**Comment by Galthariel** [comment]
> > On mine, everything is clickable and usable. Have you tried to Clear Weather Widget Data? I'm on 24H2 - 26100.4351
> 
> Absolutely! I always try TShooting as much as possible before posting...
> EPatcher.mp4
> 
> Win11 Pro:
> 
> ![Image](https://github.com/user-attachments/assets/01ae6586-0834-4b40-bd0e-2ad256047926)
> 
> ![Image](https://github.com/user-attachments/assets/f8b8439e-f563-48e3-9526-aa143cb4bcef)

I was only wondering if you did clear and not saying you didn't. I wonder why yours isn't working and mine is it.  Here is a screenshot of mine, including my settings. What I noticed is that my doesn't show the second block of info "Expansive Heat" in your case nor the link for more Info. It ends at the Daily Forecast icons, however like I said both, Precipitation and Wind are clickable.

![Image](https://github.com/user-attachments/assets/f6be1193-18ed-4b93-84d1-b9968b89abd3)

**Comment by ChuckIn85085** [comment]
> I was only wondering if you did clear and not saying you didn't. I wonder why yours isn't working and mine is it. Here is a screenshot of mine, including my settings. What I noticed is that my doesn't show the second block of info "Expansive Heat" in your case nor the link for more Info. It ends at the Daily Forecast icons, however like I said both, Precipitation and Wind are clickable.
> 
> ![Image](https://github.com/user-attachments/assets/f6be1193-18ed-4b93-84d1-b9968b89abd3)

So here's something that works (kind of) that I just stumbled on...

Here are the settings I started with:

![Image](https://github.com/user-attachments/assets/34deff2d-3df4-40d5-b201-a4f290016cb0)

Just for kicks and giggles, I change this, then changed it back to the screenshot above:

![Image](https://github.com/user-attachments/assets/1dd86d77-225a-481f-abf5-d1c456ed4d3f)

Now, everything *except* "More Info" works:

https://github.com/user-attachments/assets/706ba322-b290-4408-ab17-85d1628ba98d

**Comment by pyrates999** [comment]
If the weather from google is using dynamically labeled elements in the css, hardcoding the code in the weather dll to check for them will not work.  That's why this is working for some and not others.

**Comment by davids5** [comment]
> If the weather from google is using dynamically labeled elements in the css, hardcoding the code in the weather dll to check for them will not work. That's why this is working for some and not others.

@pyrates999 

The image `ID` is dynamic - the image `class name` is static. The change picks up the images in the `class name` and then tales the 0th element.

**Comment by pyrates999** [comment]
Ok, so you're checking the class name that has the value of `YQ4gaf zr758c`?  That also sounds like it is randomly generated.

Here is the html output I think you should be checking:

`<div data-ve-view="" data-hveid="any value" data-ved="any value"><h2 class="any value">Weather Result</h2>`

So what you want to look for is the above with the text: `Weather Result`

And then look for the closing div tag:

`</div>`

But you want to be careful with this because below the initial div tag, there are more div tags that begin and then end.  And only when those end, then you look for the closing div tag.

I viewed the source, and only got one instance of: `Weather Result`

**Comment by davids5** [comment]
@pyrates999 The code was fragile to begin with. There are a lot of references to random (not dynamic) ClassNames and ID as well as Image Content data.  Since the content from the server is not under control of this organization. It will break if the server side revises any of it. Please realize I am not judging the it, but just stating a fact.  This change does not increase or decrease the fragility. It just repaired what broke. (for now)

**Comment by pyrates999** [comment]
@davids5 I understand.  Just suggesting a better way to go about it to handle dynamic class names and id's.  I do think the weather feature will always require updates made to it because it uses a dynamically generated page from google, which is subject to google thinking you're a bot trying to access it, or when you need to agree to conditions using it, such as cookies.

I do think google expects you to use their weather api though: https://developers.google.com/maps/documentation/weather/get-api-key

but that costs money, so perhaps every user here who wants to use the weather feature, will have to have a google account, each having their own weather api key.

**Comment by n3ntj** [comment]
I also have the same issue with ExplorerPatcher 'breaking' the WIN11 Widget feature. Can only get it to work by uninstalling EP. It seemed to work until recently... either there was an update to EP or to WIN11. Hopefully a future update to EP fixes this issue so I can re-install EP.

**Comment by Majoraslayer** [comment]
It looks like this issue has been going on for a lot longer than I realized.  I think my weather widget stopped working about 6 months ago and I gave up on it.  Is the dev still actively working on it, or has it been abandoned?

**Comment by davids5** [comment]
Use the dll from https://github.com/valinet/ExplorerPatcher/pull/4392

and do this: https://github.com/valinet/ExplorerPatcher/pull/4392#issuecomment-3066698894

**Comment by teddyboydave** [comment]
There was me thinking i had done something to my computer, its annoying, it used to work really well, i see mention of google, why does that not surprise me, EP is something i really like, and i want to carry on using it, as it stands now, i take it this issue still is an issue???
I dont remember when this happened, it only happened to my desktop, my laptop EP still works??.

**Comment by ABAL1412** [comment]
I have the same problem. Don't know why it's so unstable.

**Comment by cjahn50** [comment]
It looks like the issue has returned...

It appears that the Weather widget is having issues again. I just updated - Windows 11 (KB5063878) (26100.4946).
The version is 26100.4946.  I tried the local.state fix and it partially works. 

Update: The local state workaround partially fixed it (I use fixed loosely :-) ). So I tried the ep_weather_host.dll from this link - https://github.com/valinet/ExplorerPatcher/pull/4392 and so far it's stable.

**Comment by Ovrikh** [comment]
> Use the dll from [#4392](https://github.com/valinet/ExplorerPatcher/pull/4392)
> 
> and do this: [#4392 (comment)](https://github.com/valinet/ExplorerPatcher/pull/4392#issuecomment-3066698894)

Working fine on 22631.5335.68.2 with windows 11 24h2 build 26100.4946

**Comment by Amrsatrio** [comment]
Fixed in 69.2.

**Comment by ITManCHINA** [comment]
> Fixed in 69.2.

Hi, ep 26100.4946.69.2 with Windows 11 23H2 22631.5909, still don't work, sad.

<img width="1414" height="928" alt="Image" src="https://github.com/user-attachments/assets/f26e3794-b73a-4cb1-8e87-ed030431aaf9" />

**Comment by pyrates999** [comment]
Lets see if the class name has changed.  Please do the following for anyone who is having problems with this:

1. Go to google.com
2. Search for: `weather your location`
3. Replace `your location` with your city followed by your province/state followed by your country
4. Example: `weather Ottumwa Iowa USA`
5. Right click on the weather shown and select `View page source`
6. Do a search for: `YQ4gaf zr758c`
7. It should show something like this:

<img width="778" height="58" alt="Image" src="https://github.com/user-attachments/assets/7542165a-e05c-4f16-9715-3008926665d9" />

I had 23 results found.  If you're not getting any results, it can't find the class name and thus, it shows that error message.

Now I've been able to activate weather again, so I can test this.  And it still showed this to me:

<img width="674" height="319" alt="Image" src="https://github.com/user-attachments/assets/2b8fd6c6-29fa-4cf9-8cbf-2ecabb52e9b4" />

I'm on the 69.4 release.

I noticed a very brief error message being shown, but could not capture it by pressing print screen.  So I captured it using OBS Studio as video.

I found the frame it was shown on:

<img width="674" height="281" alt="Image" src="https://github.com/user-attachments/assets/c712328a-8c27-43cc-a6cd-c718b26ab9ce" />

Google thinks you're a bot!

I think the fix for this is if the class name `YQ4gaf zr758c` can't be found, offer to allow to show the page as is and then you can go  through it and accept cookies if needed, or in my case, prove I'm not a bot.

**Comment by Galthariel** [comment]
@pyrates999

Followed your suggestion and tried

    Went to google.com
    Search for: weather my location
    Replaced my location with my city followed by your province/state followed by your country
    Right click on the weather shown and select View page source
    Did a search for: YQ4gaf zr758c
  
Got **zero** results instead of the 23 you got

**Comment by pyrates999** [comment]
just to be sure, please put what you searched for.  It should not be `weather my location`.  You're supposed to replace `my location` with your city province/state and country.

**Comment by Galthariel** [comment]
I did

**Replaced** my location with my city followed by my province/state followed by my country

**Comment by pyrates999** [comment]
Ok just making sure.  Did you see weather for your location then?  Did you right click in the area where weather was being shown and click on `View page source`?  And then when searching for `YQ4gaf zr758c`, you got no results?  There was no spaces in the search before and after `YQ4gaf zr758c`?

**Comment by Galthariel** [comment]
Ok Sorry, I think I had an extra space between "YQ4gaf zr758c" the first and second time I tried

After correcting, I did get 9 (not 23) of **"YQ4gaf zr758c"** results and only **ONE** (First) has the exactly same result you mentioned of **alt="Cloudy" data-deferred="1" class="YQ4gaf zr758c" height="60" width="60"></div><div jscontroller="e0Sh5"**

The other 8 has "YQ4gaf zr758c"  but not the full sentence like you mentioned.

**Comment by pyrates999** [comment]
Good.  Then I suspect the reason why it's not working for you in the taskbar with EP is because like me, google thinks you're a bot.

**Comment by Galthariel** [comment]
Just for further investigation, I do have both, cookies and location enabled (allow)

**Comment by Galthariel** [comment]
Just right-clicked again and instead of page source I pick inspect and found 46 errors, most of them with "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT"

**Comment by Galthariel** [comment]
The ones above are errors and there are also issues.

![Image](https://github.com/user-attachments/assets/2a33a74d-f3bf-4bc3-a084-04d0fb28539c)

**Comment by pyrates999** [comment]
> Just right-clicked again and instead of page source I pick inspect and found 46 errors, most of them with "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT"

What browser are you testing this from?  I'm using google chrome.

**Comment by Galthariel** [comment]
Chrome as well.

**Comment by pyrates999** [comment]
The errors in chrome are not relevant here.  EP only cares if the class name `YQ4gaf zr758c` exists.  If it does not, it will show the error message of no internet connection for weather.

**Comment by pyrates999** [comment]
So I got the error message without it being cut off:

<img width="404" height="180" alt="Image" src="https://github.com/user-attachments/assets/036ed212-434d-4974-9a1d-4f440aab8bf3" />

I tested the url in chrome, it worked.

And then tested it in Edge, where it showed me the error message that google thinks you're a bot:

<img width="443" height="651" alt="Image" src="https://github.com/user-attachments/assets/cd49173f-a491-4986-a292-eebf099e8f4d" />

Here's the url that EP weather seems to use that I've made generic: `https://www.google.com/search?hl=en-GB&q=weather%20your%20location&sei=Z3_sal-mHbu90PEPkeHE4QE`

Replace `your%20location` with your city followed by state/province followed by country.  Use `%20` for each space, but do not use the `+` symbol as EP uses `%20` for spaces right now.

So for example with location: `Ottumwa Iowa USA`

This would be the url: `https://www.google.com/search?hl=en-GB&q=weather%20Ottumwa%20Iowa%20USA&sei=Z3_sal-mHbu90PEPkeHE4QE`

Open up Edge and go to that url.  If you get a similar error message with the prove you're not a robot, that is why EP weather is not working for you and shows the no internet connection error message.

---

As for how to fix this, if EP would allow the page to finish loading, then we could click on the `I'm not a robot`, and the page would be reloaded showing the weather.

But if EP only shows the error message and doesn't show the graphic that has I'm not a robot, the component to allow for that to load needs to be added to EP's WebView2.

**Comment by m4rm0l-ux** [comment]
Hi there!
Still having the issue

Windows 11 Pro 25H2 26200.6899
ExplorerPatcher 26100.4946.69.5
Webview2 edge runtime installed

Can't make it work:

Unable to load weather information
Make sure that the location you have entered is correct.
Verify that you are connected to the Internet.

[Reload](epweather://refresh)

tried every work around posted above ... any other help?

Thanks!

**Comment by pyrates999** [comment]
see this work around: https://github.com/valinet/ExplorerPatcher/issues/4536#issuecomment-3343778004

It may or may not work.  And it may come back, which means you'll need to do it again each time it happens.

See my above comment why.

**Comment by m4rm0l-ux** [comment]
> see this work around: [#4536 (comment)](https://github.com/valinet/ExplorerPatcher/issues/4536#issuecomment-3343778004)
> 
> It may or may not work. And it may come back, which means you'll need to do it again each time it happens.
> 
> See my above comment why.

It worked, thank you very much, indeed

**Comment by Mefisst** [comment]
I run caniwebview2-v1-0 https://github.com/valinet/ExplorerPatcher/issues/4536#issuecomment-3343778004
I did everything as needed and confirmed that I am not a bot, copied the folder "Default" and file "Local State"

widget works partially. shows the current weather, but when you click on the widget you can no longer see the weather for other days and whatever you choose, scrolling doesn’t work either

if you click ExplorerPatcher in the settings and click update the weather, it stops working completely again

you also need to specify the city in the settings ExplorerPatcher, if you leave it at default, the weather icon becomes incorrect, the text is correct

Why not give me the opportunity to confirm directly in the widget that I’m not a bot?

**Comment by gtdurham** [comment]
Not exactly sure what's happening, but without changing anything, the weather widget seems to be working again, but don't know for how long.

**Comment by pyrates999** [comment]
See my comment for why it sometimes works and sometimes doesn't.
