### ISSUE TITLE
New version of ExplorerPatcher 22621.1992.56.3 does not work. Crash, reload and restart. Windows 11 Version 22H2

### ISSUE THREAD

**Issue by Gxtod** [valinet/ExplorerPatcher#1935]
**It does not fix errors**, as before, when you click on a folder with the mouse, when you open a folder with attachments, files crash and ExplorerPatcher closes, it goes into reboot and after a while everything repeats.
Please fix this terrible error, at the moment it is simply impossible to use the ExplorerPatcher, because. it constantly crashes, falls into an error and reboots.

P.S. _Yes, I put special symbols, followed the recommendations, deleted lines in the registry, rearranged your ExplorerPatcher several times, and alas, this never helps, did not help me!_

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.

**Comment by Poopooracoocoo** [comment]
#1798

**Comment by Gxtod** [comment]
> Please post windows version and build. You can find this by running winver.

Windows 11 Enterprise - **22H2**
OS Build: **22621.2134**
Windows Feature Experience Pack **1000.22659.1000.0**

**Comment by zerosquared** [comment]
Confirmed.  Still having issues with the taskbar.  Every time I right-click it, EP just reboots itself.  I can't get to any menu options or change any properties of it.

Also running:
Windows 11 Enterprise - 22H2
OS Build: 22621.2134

**Comment by qounik** [comment]
Been using without explorer for a day now. 
Windows 11 Pro - 22H2
OS build: 22621.2215

**Comment by SepticFuddy** [comment]
Same issue on this and the previous version at least. Not sure if it is EP that changed or Windows, but right clicking the taskbar causes it to crash without fail even after reinstall.

W11 Pro 22H2 (22621.2134)

**Comment by qounik** [comment]
Fixed now after auto update. Thanks (～￣▽￣)～

**Comment by TheLostHoosier** [comment]
Same. 
Edition	Windows 11 Home
Version	22H2
Installed on	‎3/‎21/‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

**Comment by descentfan1975** [comment]
I have the same issue. It crashes on install, then when I right-click on the taskbar it crashes over and over until I get the message that it crashed 3 times in 10 seconds.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by Gxtod** [comment]
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

I already saw your answer in another topic, the instruction you provided does not help, I performed this action, alas, it does not help and does not solve the problem...

**Comment by pyrates999** [comment]
This should be closed as it is a duplicate of https://github.com/valinet/ExplorerPatcher/issues/1828

**Comment by Gxtod** [comment]
> This should be closed as it is a duplicate of #1828

I will close the ticket when there is a fix for this issue. I'm tired of turning a blind eye to emerging problems and rolling out frank hack-work and fiction under the guise of a working solution.
Either programmers and developers are engaged in a project, or they receive a bunch of tickets with requests to fix existing bugs that interfere with the normal functionality of the program!
**Make and release a normal good fix that solves this problem.**

**Comment by zerosquared** [comment]
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

And how, exactly, do I get to Properties if every time I right-click the taskbar - IT CRASHES?!?

**Comment by pyrates999** [comment]
to run the explorer patcher properties application, run this from the run menu:
C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI

**Comment by pyrates999** [comment]
@Poopooracoocoo please close this as it is a duplicate of https://github.com/valinet/ExplorerPatcher/issues/1828

**Comment by Gxtod** [comment]
> to run the explorer patcher properties application, run this from the run menu:
> C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI

It doesn't work, do you understand it or not? I followed your recommendations, enabled and disabled the "Do not change the taskbar context menu" checkbox. ExplorerPatcher still crashes when opening a folder, this solution **DOES NOT WORK!**

No need to close the topic, it will be closed when there is a ready fix, a solution to the problem, and not fiction and empty recommendations...

**Comment by badaz** [comment]
For me, this:

> to run the explorer patcher properties application, run this from the run menu: C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI

combiend with this:
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

fixed the problem (Windows 11 22H2 build 22621.2134)

**Comment by rahaaatul** [comment]
Doesn't fix for me, clicking on windows icon doesn't open start menu, or the tab switcher does not work. 

OS BUILD: `22621.2134`

**Comment by pyrates999** [comment]
Then you gotta wait for this to get fixed.

**Comment by Donglin216** [comment]
Enabling "Do not change the taskbar context menu" fixed the problem for me, but I really wish an actual fix was given for this cause I really do not like the windows 10 taskbar.

**Comment by descentfan1975** [comment]
> to run the explorer patcher properties application, run this from the run menu: C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI

This worked for me, as long as the Taskbar style was set to Windows 10, not Windows 11.

**Comment by Donglin216** [comment]
> > to run the explorer patcher properties application, run this from the run menu: C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI
> 
> This worked for me, as long as the Taskbar style was set to Windows 10, not Windows 11.

Ye setting the windows taskbar to 11 will remove the properties tab and a few others altogether because of the "Do not change the taskbar context menu"

**Comment by TPuschl** [comment]
same for me. Windows 11 22H2 Build22621.2134
ExplorerPatcher Crashes all the time. Also enabling "Do not change the taskbar context menu" doesn't help as workaround.
Taskbar Style ist Windows10 and must stay as only here folder "links" etc. can be enabled in Taskbar

**Comment by Donglin216** [comment]
> same for me. Windows 11 22H2 Build22621.2134 ExplorerPatcher Crashes all the time. Also enabling "Do not change the taskbar context menu" doesn't help as workaround. Taskbar Style ist Windows10 and must stay as only here folder "links" etc. can be enabled in Taskbar

Ye using windows 11 taskbar with the option enabled prevents the user from opening the properties tab again unless they use the CMD command to open it

**Comment by XiaoPanPanKevinPan** [comment]
Windows 11 22H2 (build 22621.2134) 

After updating to this version, the desktop environment simply doesn't appear. But strangely, after reinstalling ExplorerPatcher, it works again. 

I've set my taskbar style to "Windows 10".  This style doesn't seem to be affected by the issue that right-clicks cause Explorer crash.

**Comment by CrustyTheCoin** [comment]
I have a combination of all the issues. When clicking on Start Menu button, nothing happens, and right clicking caused the taskbar to crash and restart. Also tried reinstalling after deleting registry entries for ExplorerPatcher and rebooting, but now none of the ExplorerPatcher functions work, and my taskbar looks and functions like the standard Windows 11 one even though EP is installed and active, and programs are stacking on the taskbar like the standard Windows 11 behaviour.

Disabling the option for "Do not change the taskbar context menu" does stop the taskbar from crashing, but then no way apart from command line option to get to ExplorerPatcher Properties.

I didn't have any problems with the same build of Windows, and an older version of EP (sorry can't remember what version I was on before), but as soon as I updated to the latest version of EP a couple of days back my troubles started.

Windows 11 Pro 22H2 (Build 22621.2215)
ExplorerPatcher 22621.1992.56.3

**Comment by pyrates999** [comment]
You probably don't have symbols downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

As for deleting all the registry entries, that's why EP stopped changing anything.  Uninstall it and install it again and wait for the symbols to be downloaded before you do anything.

**Comment by CrustyTheCoin** [comment]
I did wait for the symbols but they never downloaded even after waiting 30 minutes without clicking anything. After reinstalling and waiting 30 minutes, every time I right clicked on the taskbar and it restarted I would see a notificiation saying that it downloaded the symbols....

As far as the Windows versions, it may be a preview I am not sure, but I do not have the option enabled for "Get the latest updates as soon as available". It is turned off for me. I may have manuually done that update when it was offered to me in Windows Update at some stage, but I do not have the "Get the latest updates as soon as available" option enabled as I know Microsoft too well, and would never install any betas from them, so it is not any automatic updates to betas causing the issue.

**Comment by pyrates999** [comment]
Read here to make sure symbols are set to be downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

Then check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

to run the explorer patcher properties application, run this from the run menu:
C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI

If you have a third party firewall installed disable it while installing EP.

**Comment by TPuschl** [comment]
I fixed the issue by uninstalling FileExplorer, Restarting Windows11 and installing FileExplorer again. Thx guys for all your support and suggestions.

**Comment by igroglaz** [comment]
22621.2134
I reinstalled but still have crushes after I open a folder from desktop shortcut... old versions worked like a charm

**Comment by pyrates999** [comment]
> 22621.2134 I reinstalled but still have crushes after I open a folder from desktop shortcut... old versions worked like a charm

Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. The new version should never do irrecoverable crashes like these anymore. There should be no more major issues on 22621 builds up to 22621.2359.
