### ISSUE TITLE
Taskbar is fully transparent

### ISSUE THREAD

**Issue by CJ-Foxfield** [valinet/ExplorerPatcher#2988]
I'm using Windows 11 Pro OS Build: 22631.3296 and with the latest ExplorerPatcher Version 2261.3007.63.2 the patcher section of my taskbar has become fully transparent so is very difficult to see.

**Comment by grimmute** [comment]
Please take a look at open issues before opening a new one.

This is already fixed: https://github.com/valinet/ExplorerPatcher/issues/2975

**Comment by CJ-Foxfield** [comment]
It is not fixed. I'm sorry I should have added that I'm using Windows10 taskbar style. The Explorer Patcher Change log states 
Taskbar10: Revised the method for restoring acrylic to the Windows 10 taskbar on 22621+. (5e7bad2)
    This should fix the taskbar being fully transparent on recent builds such as 22635.3066 and 22621/22631.3296 despite not having any other customization software.

I don't have any other customization software and I'm not using 22635.3066 and 22621/22631, I'm using 22631.3296 which I got this morning. I also not that this latest update has been tested on OS builds 22000.2538, 22621.1992, 22621.3155, 22621.3235, 22621.3296, 25951.1000, and 26058.1000 and not on 22631.3296

**Comment by fr3deric** [comment]
That solved it for me. Thank you @grimmute

**Comment by danmcco** [comment]
Solved it for me too.

**Comment by CJ-Foxfield** [comment]
I tried, I clicked on the pre-release number and downloaded  ep_setup.exe but for some reason it won't run. I've tried right clicking the file and selecting run as administrator, I get a beep but it still doesn't run.

**Comment by mebogh** [comment]
Same issue here after W11 update, with W10-style taskbar on left side. Pre-release solves it.

**Comment by AKVADUS** [comment]
I have the left-side taskbar, and I definitely like this transparent bug. It might be a nice option for EP to have the transparent feature. 
![Transparent](https://github.com/valinet/ExplorerPatcher/assets/163304153/0a5ad625-e851-4081-871f-c950fa0f9c58)

**Comment by musictopia2** [comment]
I have been unable to even download the prerelease.  When I go to the link provided, I see no option to even download.  I wish the release would be made public so when I click on updates, then it can update it.

**Comment by Atid-Gharbi** [comment]
@CJ-Foxfield don't download the exe. Just go to Updates settings and check "Receive pre-release versions". Then check for updates.
The pre-release did fix the transparent taskbar for me.

**Comment by musictopia2** [comment]
Thanks for letting me know.

**Comment by CJ-Foxfield** [comment]
Yea, thanks for that. Fixed now 🙂

**Comment by opus-x** [comment]
Sorry to bother, but It's not fixed when it's a pre-release. I do agree it's a duplicate.
For a temporary fix when using OpenShell and for those who want to wait for an official release, read this:
https://github.com/valinet/ExplorerPatcher/discussions/1807#discussioncomment-8768138
