### ISSUE TITLE
After the windows11 is updated, win10 tiles cannot take effect.

### ISSUE THREAD

**Issue by korahstyle** [valinet/ExplorerPatcher#3162]
2024-04 for Windows 11, version 23H2 x64. NET Framework 3.5 and 4.8.1 cumulative update preview (KB5037591)
2024-04 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5036980)
After these two updates, the win10 tile effect does not take effect, and it is impossible to restart the settings.

**Comment by Cyberdr3am** [comment]
same here

**Comment by FlowAlive** [comment]
same here

**Comment by ChrAlpha** [comment]
same

setting `start menu style` to window 10 dosn't work on my pc

![image](https://github.com/valinet/ExplorerPatcher/assets/53332481/ca4324c2-1d40-4b64-89ba-a52cbb48a82f)

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by Silver-Fox** [comment]
after KB5036980 I had to reinstall and patch all of my themes and plugins to get them working but no matter how hard I try I cant get windows 10 start menu back. glad I'm the only one facing this issue.

**Comment by zake2002v2** [comment]
The problem is, while using the latest preview does seem to fix it, Microsoft Defender sees it as malware unlike the latest stable release, plus who knows if the preview release would actually break your system?

**Comment by PolarisSdesu** [comment]
Fixed!
just update to the [Latest Preview](https://github.com/valinet/ExplorerPatcher/releases/download/22621.3296.64.3_47cc165/ep_setup.exe)

**Comment by smithy1294** [comment]
Im still having the issue where it see's the preview as a virus and can't figure out how to get around that

**Comment by icetd** [comment]
Same Here

**Comment by mustafatoktas** [comment]
@PolarisSdesu doesn't work "pin to start"

win 11 home
22631.3527
Windows Feature Experience Pack 1000.22700.1003.0

**Comment by rmz4ed** [comment]
If Windows blocks the Latest Preview as a virus, go to Windows Security -> Virus and Threat Protection -> Protection History and allow the file to be downloaded. The Latest Preview fixed the Windows 10 start menu for me.

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3066

**Comment by meuskas** [comment]
> @PolarisSdesu Winows10 start menu is working but doesn't work "pin to start" feature.
> 
> Windows 11 Home 23H2 22631.3527 Windows Feature Experience Pack 1000.22700.1003.0

i am having this same issue :/
