### ISSUE TITLE
The Weather widget cannot be read because of Google settings

### ISSUE THREAD

**Issue by Toncino** [valinet/ExplorerPatcher#3357]
First of all, thanks a lot for the wonderful tool, really appreciated your support on this!

Here comes the issue: when I click on the Weather widget, the Google settings do not allow me to read it:

![image](https://github.com/valinet/ExplorerPatcher/assets/75485222/919a4f2e-4fde-43cb-80b7-3338967e99c9)

Any suggestion on how to fix this?

Thanks!

**Comment by Toncino** [comment]
I just realized this was already reported here: 

https://github.com/valinet/ExplorerPatcher/issues/934

but I still haven't understood how to fix it...

**Comment by pyrates999** [comment]
It was fixed by updating the code in EP.  So keep this open.

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by farmaher** [comment]
Any update on this?

![image](https://github.com/valinet/ExplorerPatcher/assets/35561612/b74ae65f-e95e-4e6d-9e30-769824e9fe48)

**Comment by pyrates999** [comment]
It was fixed in the latest release of EP.  Just check for updates and install the latest update.

**Comment by farmaher** [comment]
I am on the latest release:

![image](https://github.com/valinet/ExplorerPatcher/assets/35561612/00a00d72-c940-4534-9cad-c9de10903da4)

**Comment by farmaher** [comment]
I even uninstalled, re-installed, and reset settings, but none didn't fix the issue.

**Comment by pyrates999** [comment]
Oh I thought you were talking about the gray bar at the top of the weather window.  That is what was fixed in the release.

**Comment by farmaher** [comment]
No, google settings dont go away. As said, uninstall, re-install, restart and reset to default didn't help. Shall I open a new ticket for this?

**Comment by pyrates999** [comment]
This is the ticket for this.  No need to open another.
