### ISSUE TITLE
opening home in explore cause to crash (inportant)

### ISSUE THREAD

**Issue by xxxprosoldierxxx** [valinet/ExplorerPatcher#3447]
this is waht happen when i go home page 

https://github.com/valinet/ExplorerPatcher/assets/87656180/df3dc626-d405-4ee8-9a3c-2cf655820326

yes it dose this but dosent crash when i open new tab

https://github.com/valinet/ExplorerPatcher/assets/87656180/3264f458-7c18-4f8c-8923-4f74cca617c7

is there way to fix this?

**Comment by xxxprosoldierxxx** [comment]
if anyone has this problem idk waht it cause

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by xxxprosoldierxxx** [comment]
![Screenshot 2024-07-06 113647](https://github.com/valinet/ExplorerPatcher/assets/87656180/d35bf140-e9a2-46d0-9ad5-35bd03d96a1e)
here

**Comment by pyrates999** [comment]
try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_9844324

**Comment by Amrsatrio** [comment]
@pyrates999 That prerelease does not contain the fix.

@xxxprosoldierxxx Yes, I understand. I plan to make a fix for this by this week. Strangely enough this doesn't happen in any 24H2 version.

**Comment by pyrates999** [comment]
@Amrsatrio I suggest that the release notes shown on the builds page that has releases and pre-releases link to the issues that have been fixed.

**Comment by PeterVLee** [comment]
I have been having the same issues and can consistently replicate it when using the Win 10 Ribbon or Win 7 Command Bar options for the file explorer
<img width="399" alt="image" src="https://github.com/user-attachments/assets/666b1564-e8ed-4bcf-a4e0-5dc6f806757e">

This doesn't seem to happen with either of the Win 11 control interfaces.

@Amrsatrio If you are still working on the issue, I have some sample crash dumps if they will help. Thank you for working on this.
[CrashDumps.zip](https://github.com/user-attachments/files/16184618/CrashDumps.zip)

ExplorerPatcher ver: 22621.3527.65.5
Win ver: 23H2 OS Build 22631.3880

**Comment by xxxprosoldierxxx** [comment]
so the bug is fixed?

**Comment by pyrates999** [comment]
If it no longer is crashing for you, please post your windows version and build, and EP version that you are running.

**Comment by PeterVLee** [comment]
Slightly necroing this issue to say that this crash still occurs as described in the OP. I saw an [older thread](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6676420) saying to delete some keys located in `HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell` but this did not work for me.

**Comment by pyrates999** [comment]
can you link to the comment that said to delete some keys in `HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell`.

**Comment by PeterVLee** [comment]
I linked it as markdown in my comment, though maybe it's not showing up. Here:

https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6676420

**Comment by PeterVLee** [comment]
Yes, I have powertoys' explorer add-on enabled.

**Comment by pyrates999** [comment]
Uninstall powertoys explorer add-on, reboot and see if the crashes stop.

**Comment by Amrsatrio** [comment]
@pyrates999 Does not help. I haven't fixed this.

**Comment by JordOfTheFlies** [comment]
I have a similar result, only it'll let me go to home once, then if I navigate to a different destination and click home again it'll crash reliably. So Downloads > Home = Fine, but Home > Downloads > Home = Crash.
That said, I do have some WinAeroTweaker settings applied so it's plausible that's a contributing factor. Also some of the Stardock software like Fences, but in theory none of that should touch regular explorer windows.

I can confirm that switching from the ribbon menu back to normal Windows 11 style does cause it work normally for me. If only the new style wasn't so needlessly bulky (also the 'shrink/disable' address bar tweaks only seem to apply to non-11 styles, so it might be worth stating that on the options for clarity)

**Comment by Amrsatrio** [comment]
Fixed in 69.6.
