### ISSUE TITLE
Right-click not working 

### ISSUE THREAD

**Issue by codebaragi23** [valinet/ExplorerPatcher#3595]
version: 
![image](https://github.com/user-attachments/assets/dc9460a4-b07d-499f-a8ad-ca82f3ab36bb)

setting:
![image](https://github.com/user-attachments/assets/b1620e4d-38cc-4518-a174-875d0cf8bc32)

The taskbar functions normally when "location on screen" positioned on the left, right, or bottom, but when it's at the top, the right-click menu in the app doesn't appear.

**Comment by pyrates999** [comment]
Install latest pre-release of EP: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment]
What do you mean by "right click menu in the app"?

**Comment by pyrates999** [comment]
I think they are referring to this: https://github.com/valinet/ExplorerPatcher/issues/3587

which was already fixed.

**Comment by Amrsatrio** [comment]
Ok then, @codebaragi23 please download the latest prerelease and don't forget to configure exclusions and don't forget to disable realtime protection when downloading it.

**Comment by BirukTes** [comment]
Same issue still on latest install, recently upgraded from win 10 to 11... right click did not work:
<img width="187" alt="{9626D65E-DEB9-484A-A45B-48D76E825E40}" src="https://github.com/user-attachments/assets/40047665-cdc8-4581-964f-b4dff6aab184">

**Comment by BirukTes** [comment]
Okay, but it downloaded the necessary "symbols" for the OS build after the upgrade... in any case it still does not work after restoring to default and rebooting, note though the issue seems to be only for the TOP position, it works for others.

**Comment by pyrates999** [comment]
Hi @Amrsatrio,

Please check if right clicking works on windows 11 when taskbar is set to windows 10 (ExplorerPatcher) and it is on top, not on the bottom.

**Comment by codebaragi23** [comment]
> Install latest pre-release of EP: https://github.com/valinet/ExplorerPatcher/releases

it work. thank you

**Comment by codebaragi23** [comment]
> Ok then, @codebaragi23 please download the latest prerelease and don't forget to configure exclusions and don't forget to disable realtime protection when downloading it.

Thank you. It work well.

**Comment by BirukTes** [comment]
@codebaragi23, glad that it worked for you, however, I have even completely uninstalled and installed back the latest EP (same as pre-release), the app contextmenu when on the TOP position still does not work.

**Comment by BirukTes** [comment]
Weirdly, it got removed/uninstalled after shutting down the pc... no trace of it. I wonder if Win 11 removed it purposely..?

**Comment by pyrates999** [comment]
> Weirdly, it got removed/uninstalled after shutting down the pc... no trace of it. I wonder if Win 11 removed it purposely..?

Read the release notes here on what changes you need to make with your AV: https://github.com/valinet/ExplorerPatcher/releases

**Comment by BirukTes** [comment]
I suppose, it has something to do with the new Windows 11 taskbar, because the render the of the jump list is the exact of that... just a speculation, it may not know how to render on that position... but likely a bug.

**Comment by BirukTes** [comment]
Thank you all!! Latest pre-release from yesterday just fixed it! https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.5_5094108
