### ISSUE TITLE
No window switcher is working

### ISSUE THREAD

**Issue by jdp1024** [valinet/ExplorerPatcher#525]
I upgraded EP from 22000.348.39.2 (which works perfectly) to 22000.348.40.5 in a real laptop. After epsetup ran, Alt+Tab doesn't work any more: nothing shows upon the key press. A random item of the the context menu of the task bar menu is collapsed. I tried to restart Explorer from the settings dialog, but a new Explorer window popped up. I used Task Manager to kill Explorer and ran it again, the window switcher is always the Windows NT style.

Strange enough, 22000.348.40.5 (also upgraded from 22000.348.39.2) works perfectly in a Parallels Desktop virtual machine.

Please let me know what I can provide to help locating the problem.

**Comment by valinet** [comment]
Enabling the console and watching some output there is a good start (Properties - Advanced - Enable console).

What Alt-Tab setting you have? There are 4 options now. Which ones do not work?

Try deleting the registry key at HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher\sws

**Comment by jdp1024** [comment]
1. All 4 settings for Alt+Tab work as Windows NT style.

2. I enabled console output, here is what I get:

```
funchook create 1
[Symbols] Identified known "twinui.pcshell.dll" with hash 3f6ef12a59a2f84a3296771ea7753e01.
[Symbols] Identified known "StartDocked.dll" with hash 7e652d78661ba62e33d41ad1d3180344.
Loaded symbols
Setup user32 functions done
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup sndvolsso functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
[Positioning] Added settings for monitor 0000000000010001 : 0
>>> Signal shell ready.
Ended "Signal shell ready" thread.
Started "Open Start on current monitor" thread.
Progman: 66020
Progman hook: 66123
[Positioning] Removed settings for monitor: 0000000000010001
[Positioning] Added settings for monitor 0000000000010001 : 0
0 0
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\WINDOWS\dxgi.dll
[Updates] Checking against hash "b8f42ca717b6df84720993ae8ed8af5e"
[Updates] Update URL: https://api.github.com/repos/valinet/ExplorerPatcher/releases?per_page=1
[Updates] No updates are available.
```

3. My real laptop is a ThinkPad with a TrackPoint pointing device, when using 22000.348.39.2, I can use the middle button and move the pointer to scroll the window, but with 22000.348.40.5, after several scrolling operations, I get 60% CPU usage on system interrupts and I can see in Task Manager that over 20 Synaptics Pointing Device Helper processes (SynTPEnh.exe) are running. If I don't use middle button with the pointer, this doesn't happen.

4. After removed the registry key `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`, the Windows 11 window switcher came back.

5. I upgrade to .6, nothing shows (NO any window switchers) when I press Alt+Tab.

**Comment by jdp1024** [comment]
> Does the video acceleration and DWM work?

They both work in real and virtual machines.

**Comment by valinet** [comment]
What Windows build?

**Comment by BraINstinct0** [comment]
FYI LG Gram here, no issue for both 22000.348.5 and 6.
windows 22000.348 here(for reference.)

**Comment by valinet** [comment]
> My real laptop is a ThinkPad with a TrackPoint pointing device, when using 22000.348.39.2, I can use the middle button and move the pointer to scroll the window, but with 22000.348.40.5, after several scrolling operations, I get 60% CPU usage on system interrupts and I can see in Task Manager that over 20 Synaptics Pointing Device Helper processes (SynTPEnh.exe) are running. If I don't use middle button with the pointer, this doesn't happen.

Let's try to exclude additional things that could cause problems. Use a regular mouse for testing initially. Once we identify the problem there, solve it, we come back and check with TrackPoint as well... seems logical to me. Also, what Windows build?

**Comment by valinet** [comment]
40.6 adds nothing, I fixed some bug in the GUI. Try to separate issues and think through them logically, otherwise this will never be solved. Delete the registry entry again, check what works. Test setting each of the 4 window switchers and see which works and how it behaves.

**Comment by valinet** [comment]
Also, delete AltTabSettings in HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer, that controls which window switcher shows. Without an entry, you should get the Windows 11 one. After that works, enable each of the other ones and see which works.

**Comment by jdp1024** [comment]
Windows build is Version 10.0.22000.348.

I deleted `AltTabSettings` in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer`. Then Windows 11 default window switcher was back.

I used a Logi mouse.

Then I switched to Simple Window Switcher and restarted Explorer: then the window switcher is Windows NT style, and just one time the switcher showed, it never showed again when I pressed Alt+Tab.

Then I switched to Windows 10 mode and clicked "Restart File Explorer": then a new Explorer window showed. I clicked "Restart File Explorer" again, the Explorer restarted, this time the window switcher was still Windows NT style.

Then I switched to Windows 11 mode and restarted Explorer, this time it was Windows 11 default window switcher.

Then I switched to Windows NT mode, then the window switcher was Windows NT style.

**Comment by jdp1024** [comment]
I ran WinDbg x64 on the ThinkPad to analyze the dump file. Here is what I've got:

```
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

DEBUG_FLR_EXCEPTION_CODE(8000ffff) and the ".exr -1" ExceptionCode(c0000409) don't match

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 5

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on LAPTOP-XXXX

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 70

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 143

    Key  : Analysis.System
    Value: CreateObject

    Key  : Timeline.Process.Start.DeltaSec
    Value: 79


NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  (.ecxr)
rax=00000000008bddb0 rbx=00000000008be330 rcx=00000000008bddb0
rdx=00000000008be260 rsi=00000000008be330 rdi=00000000008bddb0
rip=00007fffefb123f2 rsp=00000000008bdcd0 rbp=0000000000000001
 r8=0000000000000000  r9=00000000008be220 r10=00000ffffdf62455
r11=0000000000200000 r12=0000000000000001 r13=0000000000000000
r14=0000000000000000 r15=00007fffd41bd350
iopl=0         nv up ei pl nz na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000204
KERNELBASE!RaiseFailFastException+0x152:
00007fff`efb123f2 0f1f440000      nop     dword ptr [rax+rax]
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fffd41bd350 (twinui_pcshell!winrt::Windows::Internal::Shell::XamlExplorerHost::implementation::XamlExplorerHostWindow::FailFastIfNotOnCreationThread+0x0000000000222080)
   ExceptionCode: c0000409 (Security check failure or stack buffer overrun)
  ExceptionFlags: 00000001
NumberParameters: 3
   Parameter[0]: 0000000000000007
   Parameter[1]: ffffffff8000ffff
   Parameter[2]: 0000000000000127
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT

PROCESS_NAME:  explorer.exe

EXCEPTION_CODE_STR:  8000ffff

STACK_TEXT:  
00000000`008bdcd0 00007fff`d423057f : 00000000`00000000 00007fff`efb122a0 00000000`00000000 00000000`008be4e0 : KERNELBASE!RaiseFailFastException+0x152
00000000`008be2b0 00007fff`d423067e : 00000000`008be400 00000000`00000127 00000000`00960701 00007fff`f21dbc18 : twinui_pcshell!wil::details::WilDynamicLoadRaiseFailFastException+0x5f
00000000`008be2e0 00007fff`d4230654 : 00000000`00000000 00000000`008be380 00007fff`f22d01d0 00007fff`dda70078 : twinui_pcshell!wil::details::WilRaiseFailFastException+0x22
00000000`008be310 00007fff`d422c191 : 00000000`008bf9a0 00000000`008be4e0 00000000`00000127 00007fff`d3f9ad84 : twinui_pcshell!wil::details::WilFailFast+0xbc
00000000`008be3e0 00007fff`d422bdec : 00000000`00000022 00000000`08831a20 00000000`00000033 00000000`1a65ee80 : twinui_pcshell!wil::details::ReportFailure_NoReturn<3>+0x2a9
00000000`008bf8e0 00007fff`d422bedf : 00000000`00000000 00000000`1a831430 00000000`00000000 00000000`00000003 : twinui_pcshell!wil::details::ReportFailure_Base<3,0>+0x30
00000000`008bf940 00007fff`d422da7b : 00000000`00000000 00000000`00000000 00000000`008bfba8 00007fff`efa1b51b : twinui_pcshell!wil::details::ReportFailure_Hr<3>+0x5f
00000000`008bf9c0 00007fff`d41bd350 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00e87140 : twinui_pcshell!wil::details::in1diag3::FailFast_Unexpected+0x1b
00000000`008bfa10 00007fff`d3f9ad84 : 00000000`1a8318c0 00007fff`d40fcbc0 00000000`009a12b0 00007fff`f21c7551 : twinui_pcshell!winrt::Windows::Internal::Shell::XamlExplorerHost::implementation::XamlExplorerHostWindow::FailFastIfNotOnCreationThread+0x222080
00000000`008bfa40 00007fff`d3f9ad44 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000001 : twinui_pcshell!winrt::Windows::Internal::Shell::XamlExplorerHost::implementation::XamlExplorerHostWindow::~XamlExplorerHostWindow+0x18
00000000`008bfa70 00007fff`d3f9ae99 : 00000000`1a65ee80 00000000`1aa0b420 0000a1b9`4bf028f7 00000000`1aa0b420 : twinui_pcshell!winrt::impl::heap_implements<winrt::Windows::Internal::Shell::XamlExplorerHost::implementation::XamlExplorerHostWindow>::`vector deleting destructor'+0x14
00000000`008bfaa0 00007fff`efefbea0 : 00000000`1aa0b530 00007fff`d4724000 ffffffff`ffffffff 00007fff`d43b58d0 : twinui_pcshell!winrt::impl::root_implements<winrt::Windows::Internal::Shell::XamlExplorerHost::implementation::XamlExplorerHostWindow,winrt::Windows::Internal::Shell::XamlExplorerHost::XamlExplorerHostWindow,winrt::Windows::Foundation::IClosable>::NonDelegatingRelease+0x51
00000000`008bfad0 00007fff`efefbdb7 : 00007fff`d4721d01 00000000`008bfba8 00000000`008bfeb0 00007fff`effe12b0 : ucrtbase!<lambda_f03950bc5685219e0bcd2087efbe011e>::operator()+0xb0
00000000`008bfb20 00007fff`efefbd6d : 00007fff`d4721de0 00000000`00000001 00007fff`d4721de0 00000000`008bfb98 : ucrtbase!__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> >+0x3b
00000000`008bfb50 00007fff`efefcab8 : 00007fff`d4721de0 00007fff`0000000d 00007fff`0000000d 00000000`008bfb90 : ucrtbase!execute_onexit_table+0x3d
00000000`008bfb90 00007fff`d40fca15 : 00000000`00000000 00007fff`d4103fa5 00007fff`d3f70000 00000000`008bfeb0 : ucrtbase!__crt_state_management::wrapped_invoke<int (__cdecl*)(_onexit_table_t * __ptr64),_onexit_table_t * __ptr64,int>+0x2c
00000000`008bfbc0 00007fff`d40fcb58 : 00000000`00000001 00000000`00000000 00000000`00000001 00000000`7ffe0384 : twinui_pcshell!dllmain_crt_process_detach+0x45
00000000`008bfc00 00007fff`f21dfc37 : 00007fff`d3f70000 00000000`00000000 00000000`00000001 00000000`7ffe0385 : twinui_pcshell!dllmain_dispatch+0xfc
00000000`008bfc60 00007fff`f21f41b0 : 00000000`0097de80 00007fff`d3f70000 00000000`00000000 00000000`0097e4e0 : ntdll!LdrpCallInitRoutine+0x6b
00000000`008bfcd0 00007fff`f21f401d : 00000000`00000001 00000000`00000000 00007fff`efef9f40 00000000`00000000 : ntdll!LdrShutdownProcess+0x170
00000000`008bfdd0 00007fff`f0b0c66b : ffffffff`00070001 00007fff`efef9f40 ffffffff`fffffffe 00000000`008bfeb0 : ntdll!RtlExitUserProcess+0xad
00000000`008bfe00 00007fff`efef9fec : 00000000`00000001 00000000`00000000 00000000`008bfe90 00007fff`effe12b0 : kernel32!ExitProcessImplementation+0xb
00000000`008bfe30 00007fff`efefa0c1 : 00000000`00000001 00000000`00000000 00007ff7`69e441b0 00000000`008bfe80 : ucrtbase!exit_or_terminate_process+0x44
00000000`008bfe60 00007fff`efeff33a : 00000000`00000001 00000000`00000000 00000000`00000000 00000000`00000001 : ucrtbase!common_exit+0x79
00000000`008bfec0 00007ff7`69bc0bc2 : 00000000`00000001 00000000`00000000 00000000`00000000 00000000`00000000 : ucrtbase!__crt_state_management::wrapped_invoke<void (__cdecl*)(int),int,void>+0x2a
00000000`008bfef0 00007fff`f0b054e0 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : explorer!__scrt_common_main_seh+0x172
00000000`008bff30 00007fff`f21a485b : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x10
00000000`008bff60 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x2b
```

**Comment by valinet** [comment]
Well, idk, it could be anything. I don't have any idea. Not much has changed between those 2 versions. Try to selectively compile the added stuff and maybe you figure out what's the culprit. I added a new function hook that does not do much: `twinui_pcshell_IsUndockedAssetAvailable`, other than that, nothing related to `twinui.pcshell.dll` changed. Yeah, idk, the exception stack doesn't ring any bell to me, unfortunately.

**Comment by jdp1024** [comment]
I compiled `22000.348.39.2` on my laptop, it worked fine. Then I compiled `22000.348.39.2` with the latest `sws`, the problems came (Windows NT style, explorer crashes, busy CPU, etc.). I will try to isolate the code which causes the problems.

**Comment by valinet** [comment]
Yeah, thanks, that’s the best thing to do, very well, and thank you very much.

**Comment by valinet** [comment]
Yeah, I rearchitected a lot in that commit, the program performs much better now when it works from a huge number of perspectives. It was needed. For example, the windows in the list are now finally the correct ones, the list is generated on demand as it’s the only reliable way, icons are fetched async in order not to block and delay the window list showing by too long etc. 

But yeah, it may have introduced some quirk, but I am sure it can be identified and we will correct it.

Thanks again for the effort.

**Comment by jdp1024** [comment]
> So it basically works with all latest code from master except `sws_WindowSwitcher.c` which is from some older commit?

Yes.

I also tried to roll back to EP's `1e4a11b` with latest sws, this caused problems in my laptop. After excluding `sws_WindowSwitcher.c`, EP worked fine again.

**Comment by valinet** [comment]
Yeah, well, it's good to know, this narrowed it down, butexcluding the latest `sws_WindowSwitcher.c` is not really a fix for the upstream. Try to narrow it down more, comment some stuff out and see maybe you isolate the problem more.

**Comment by jdp1024** [comment]
> Yeah, well, it's good to know, this narrowed it down, but excluding the latest `sws_WindowSwitcher.c` is not really a fix for the upstream. Try to narrow it down more, comment some stuff out and see maybe you isolate the problem more.

Of course. I will continue to locate which function caused the problem.

**Comment by valinet** [comment]
Great, thanks!

**Comment by jdp1024** [comment]
The problem is the infinite loop here:

`sws_WindowSwitcher.c` line `1782`:

```
        while (!(_this->hWndWallpaper = sws_WindowHelpers_GetWallpaperHWND()))
        {
        }
```

I added logs as this: 

```
static BOOL CALLBACK _sws_WindowHelpers_GetWallpaperHWNDCallback(HWND hwnd, LPARAM lParam)
{
	HWND* ret = (HWND*)lParam;

	HWND p = FindWindowExW(hwnd, NULL, L"SHELLDLL_DefView", NULL);
	if (p)
	{
		printf("FindWindow SHELLDLL_DefView=%x\n", p);
		HWND t = FindWindowExW(NULL, hwnd, L"WorkerW", NULL);
		printf("FindWindow WorkerW=%x\n", t);
		if (t)
		{
			*ret = t;
		}
	}
	return TRUE;
}
```

and enabled console output, the following contents repeated:

```
FindWindow WorkerW=0
FindWindow SHELLDLL_DefView=12b1ec6
FindWindow WorkerW=0
FindWindow SHELLDLL_DefView=12b1ec6
FindWindow WorkerW=0
FindWindow SHELLDLL_DefView=12b1ec6
FindWindow WorkerW=0
FindWindow SHELLDLL_DefView=12b1ec6
FindWindow WorkerW=0
FindWindow SHELLDLL_DefView=12b1ec6
FindWindow WorkerW=0
```

Once I clicked Show Desktop button:

```
FindWindow SHELLDLL_DefView=12b1ec6
FindWindow WorkerW=372414
[sws] Wallpaper RECT 0 0 292 79
[sws] Refreshing theme: 1
[sws] Refreshing theme: 1
[sws] Refreshing theme: 1
```

then everything began to work properly.

Since the `WorkerW` window is always a child of the desktop window, I tried to change the code to:

```
		HWND t = FindWindowExW(GetDesktopWindow(), NULL, L"WorkerW", NULL);
```

Then EP fully worked.

I hope it helps.

**Comment by valinet** [comment]
That's great. I knew that type of loop might be dangerous, but I did not have a better solution at that moment. That method is not getting any ordinary `WorkerW`. It sends a message to `Progman` that [**should**](https://stackoverflow.com/questions/56132584/draw-on-windows-10-wallpaper-in-c) create the window of the wallpaper, if not available. I need that in order to get the wallpaper from and display it in the window switcher, at least if "Include desktop" options is ticked. Although, yeah, I marginally heard about this in the past as well, it seems to cause issues for some people. For me, it always works, so I assumed it should work. it is, again, undocumented, so things like these may happen.

I will think of another solution, or a fallback at least, that should be implemented. Thanks for taking the time to investigate this, I will follow up with some solution in the upstream as well.

> Then EP fully worked.

Can you post a screenshot of the window switcher where the desktop entry is shown or confirm that it is properly shown (a rectangle of the desktop background) when the "Include desktop" option is ticked? That would be the test for this case.

Thank you very much, again, for taking the time.

**Comment by jdp1024** [comment]
Personally I never used the 'Include desktop' feature. I just found the desktop thumbnail picture is wrong, both the original code and GetDesktopWindow workaround generate the same picture.

![Switcher](https://user-images.githubusercontent.com/80762554/145446884-569a8000-be16-4883-89e5-d537fddcfc0f.png)

**Comment by valinet** [comment]
Okay, great, that makes sense. I knew the loop there was kind of dangerous, as with any infinite loop… What I do there is wait for the wallpaper HWND to be created by

**Comment by valinet** [comment]
Hit the wrong button, sorry.

Yeah, well, that code is supposed to get the HWND of the wallpaper window. It’s part of the functionality. As I said, I have to take a look at it and find a solution.

Thanks for testing it out, I will definitely take a look at it at the earliest opportunity.

**Comment by valinet** [comment]
I mitigated this in the latest version. I will study at a later time a better way, if any, to determine the wallpaper window. For now, I made sure not being able to do so (I still don't understand why it may fail), on some configurations, does not hang up the entire thing, so at least one loses just that, not the entire functionality. I or maybe someone else will probably open a future issue where a better way to determine the wallpaper will be tracked. For now, this solves this specific problem, i.e. "no window switcher working".

While I was at it, looking at your screenshot, it looked like the padding around the previews is kind of large. I guessed you would appreciate exposing the parameter as a configurable setting, so added that as well. It looks kind of out of place when the thumbnails are a bit smaller, indeed.

Thank you for the help with this, it sped things up a lot.

**Comment by jdp1024** [comment]
40.7 runs fine without "Include desktop". If desktop is included in the window switcher, Alt+Tab works the first time, with the correct desktop thumbnail picture, but after the switcher is dismissed, Alt+Tab won't bring up the window switcher.

**Comment by valinet** [comment]
Can you try with the latest commit? Check again for pre-release updates, it should find a version based on the current upstream.

**Comment by jdp1024** [comment]
> Can you try with the latest commit? Check again for pre-release updates, it should find a version based on the current upstream.

It doesn't work. DWM eats 100% CPU.

Maybe simulating a click on the 'Show Desktop' button will help?

**Comment by jdp1024** [comment]
I investigated the function `sws_WindowHelpers_EnsureWallpaperHWND`. It sends a message of 0x52c to enforce a `WorkerW` window be created, actually this is not enough.

A complete and working implementation follows:

```
BOOL sws_WindowHelpers_EnsureWallpaperHWND()
{
	HWND progman = FindWindowW(L"Progman", NULL);
	if (progman)
	{
		SendMessageTimeoutW(progman, 0x052C, 0x0d, 0, SMTO_NORMAL, 1000, NULL);
		SendMessageTimeoutW(progman, 0x052C, 0x0d, 1, SMTO_NORMAL, 1000, NULL);
		SendMessageTimeoutW(progman, 0x052C, 0, 0, SMTO_NORMAL, 1000, NULL);
		return TRUE;
	}
	return FALSE;
}
```

It works on all my PCs, including 3 laptops (ThinkPad, Dell XPS and NEC LaVie) and 5 virtual machines (by VMware and Parallels Desktop).

Now I revert to sws `c36c3be` (before the 2 commits about #525 fix) with the function above, EP works fine.

Still the infinite loop is dangerous, but using GetDesktopWindow() to get its content is dangerous too.

![Untitled](https://user-images.githubusercontent.com/80762554/145666274-e5da7269-357f-4da8-bc67-8891a1f02f8b.png)

**Comment by valinet** [comment]
Ok. So I will revert the 2 commits and integrate your code above.

How did you come up with it?

**Comment by jdp1024** [comment]
The implementation of `sws_WindowHelpers_EnsureWallpaperHWND` above is based on some RE work of a dynamic wallpaper application.

**Comment by valinet** [comment]
Okay, which one? I want to see it myself. The initial function floats around StackOverflow for a couple of years. Any idea what those messages do each of themselves? Not that it matters that much, what matters is it works, just curious. Also, do you have a black desktop wallpaper, so the thumbnail above is correct?

There is still a loop check for EnsureWallpaper, I think I should take that out as well; checking once should be enough, I think. That basically is there so it waits for a Progman window to get created. Ideally, it should also make sure those 3 messages get sent and check their result to be the expected one, whatever that might be. What’s your proposal for it?

**Comment by valinet** [comment]
Right now, the window switcher is delayed by 5 seconds when it is created specifically to wait for the desktop wallpaper to be created. The initial idea with the loop on EnsureWallpaper was that it would spin lock in there until Explorer finishes initializing, so the switcher is ready the moment the desktop is ready. I’d still like to implement that, it’s better as an idea, now the implementation is more cumbersome to get right.

**Comment by jdp1024** [comment]
> Okay, which one? I want to see it myself. The initial function floats around StackOverflow for a couple of years. Any idea what those messages do each of themselves? Not that it matters that much, what matters is it works, just curious. Also, do you have a black desktop wallpaper, so the thumbnail above is correct?
> 
> There is still a loop check for EnsureWallpaper, I think I should take that out as well; checking once should be enough, I think. That basically is there so it waits for a Progman window to get created. Ideally, it should also make sure those 3 messages get sent and check their result to be the expected one, whatever that might be. What’s your proposal for it?

The code was done several years ago. It is a very old application back from the era of Windows 7/8. I don't keep the application but the IDA file.

I googled and have found [an interesting article](https://www.cxyzjd.com/article/Just_bg/116887990) about this topic, it is in Chinese, but you can use Google Translate to get the point.

**Comment by valinet** [comment]
Okay, I will take a look, thanks.

Idk, there are so many questions for this, like, is it okay to obtain the HWND just once, when the application starts, or should it be obtained every time the switcher is to be shown? Like, does that window gets recreated at some point…? Who knows…?

**Comment by valinet** [comment]
Does that old app call that method that sends those messages more than once during the lifetime of its execution?

**Comment by jdp1024** [comment]
> Okay, I will take a look, thanks.
> 
> Idk, there are so many questions for this, like, is it okay to obtain the HWND just once, when the application starts, or should it be obtained every time the switcher is to be shown? Like, does that window gets recreated at some point…? Who knows…?

Yes, the behavior is undefined and undocumented.

If the wallpaper HWND cannot be obtained, is it better to disable the "Include Desktop" option?

**Comment by valinet** [comment]
But it should be obtainable. Why consider that case? You said with the above modifications it works for your problematic system as well. So, can you confirm it, does it work or not, does it show a preview of your desktop wallpaper in there or not? 

This old app you have been looking on, does it send the message to Progman more than at startup? Can you share the database file so I can look myself?

I want to reach a proper working solution on this and be done with it.

**Comment by valinet** [comment]
Third attempt, hopefully it now works well. Implemented the `EnsureWallpaper` check as you suggested, hopefully this is it.

**Comment by jdp1024** [comment]
I think the problem is fixed.

**Comment by valinet** [comment]
That's so great to hear! Thanks again for the support throughout this, it really helped A LOT.

**Comment by valinet** [comment]
@jdp1024 This is still not working as expected. It's actually driving me nuts. In the latest versions I removed the artificial 5s sleep when the sws window swither is created and just wait on `EnsureWallpaper` with 100 ms pauses between calls. That still does not cut it, unfortunately. It works some of the times, but often crashes `explorer.exe`. I have dumps, the crash occurs in `CDesktopBrowser::_OnWallpaperUpdate`; this function is specifically reached after those undocumented `SendMessage` calls that should generate the desktop wallpaper window. Specifically, the crash occurs here:

```
mov     [rax+6Dh], cl
```

`rax` is **sometimes** 0, so ofc it dereferences invalid memory. It is assigned a few instructions above: `mov     rax, [rbx+1B0h]`, where `rbx` is equal to the initial `rcx`, so to `this` (a `CDesktopBrowser` instance). On a high level, the problematic code looks like this:

```
*(_BYTE *)(*((_QWORD *)this+ 54) + 109i64) = *((_DWORD *)this + 176) != 0;
```

Yeah, it definitely looks like a race condition to me. It does not happen on my faster Ryzen 5900X desktop, but mostly on power saver on my laptop. I think it's actually a bug in `explorer`, as any arbitrary app could after all send those messages when the shell is restarted and have it crash. They should probably have done some check for non-NULL before dereferencing that memory, but whatever, the question now is what's there to do, besides just a dumb `Sleep` with an arbitrary value until the desktop sets itself up properly. I mean, they have a function that does a check exactly for that `this + 54` dereferenced offset to be non-NULL, called `CDesktopBrowser::_IsDesktopWallpaperInitialized`, but they forgot to call it there as well.

Accessing that function is practically impossible from the outside, as I have briefly looked (not impossible to do, but without hardcoding values). It starts with an `_`, the way they denote `private` functions, so indeed, it's not present in any vtable, unfortunately, so it'd be pretty useless to call it regardless if I somehow got a pointer to the `CDesktopBrowser` instance. But nevertheless, it could be useful, as I could copy its body in sws manually.

So yeah, do you know any proper way to get a pointer to that `CDesktopBrowser` instance, any idea...? I am looking around as well in the mean time, just wanted to post here as well, maybe you have an idea.

Thanks

**Comment by jdp1024** [comment]
I didn't find `CDesktopBrowser` in `explorer.exe` or `dwmcore.dll` through the pdb files from MS symbol server. Where is it implemented?

**Comment by valinet** [comment]
> I didn't find `CDesktopBrowser` in `explorer.exe` or `dwmcore.dll` through the pdb files from MS symbol server. Where is it implemented?

Yeah, sorry, `shell32`.

**Comment by valinet** [comment]
I guess that instead of `FindWindowW(L"Progman", NULL)`, the correct way to obtain a handle to the desktop window is how Raymond Chen says here: https://devblogs.microsoft.com/oldnewthing/20130318-00/?p=4933

The value returned in lwnd is the same as what `FindWindowW(L"Progman", NULL)` would return, only that I think the thing actually works only when the desktop has properly initialized. To make sure, I guess, we can go further and also obtain the `IShellBrowser` interface from it.

It seems that `CDesktopBrowser` implements that (look in `CDesktopBrowser::CDesktopBrowser`), along with several other interfaces and that obtained `IShellBrowser` is the same one we would get through when sending the message (?).

So something like this, the new `EnsureWallpaperHWND` method:

```
BOOL sws_WindowHelpers_EnsureWallpaperHWND()
{
	BOOL bOk = FALSE;
	HRESULT hr = E_FAIL;
	IShellWindows* spShellWindows = NULL;
	hr = CoCreateInstance(
		&CLSID_ShellWindows,
		NULL,
		CLSCTX_ALL,
		&IID_IShellWindows,
		&spShellWindows
	);
	if (spShellWindows)
	{
		VARIANT vtEmpty;
		ZeroMemory(&vtEmpty, sizeof(VARIANT));
		VARIANT vtLoc;
		ZeroMemory(&vtLoc, sizeof(VARIANT));
		vtLoc.vt = VT_INT;
		vtLoc.intVal = CSIDL_DESKTOP;
		long lhwnd = 0;
		IDispatch* spdisp = NULL;
		hr = spShellWindows->lpVtbl->FindWindowSW(
			spShellWindows,
			&vtLoc,
			&vtEmpty,
			SWC_DESKTOP,
			&lhwnd,
			SWFO_NEEDDISPATCH,
			&spdisp
		);
		if (spdisp)
		{
			IServiceProvider* spdisp2 = NULL;
			hr = spdisp->lpVtbl->QueryInterface(spdisp, &IID_IServiceProvider, &spdisp2);
			if (spdisp2)
			{
				IShellBrowser* spBrowser = NULL;
				hr = spdisp2->lpVtbl->QueryService(spdisp2, &SID_STopLevelBrowser, &IID_IShellBrowser, &spBrowser);
				if (spBrowser)
				{
					//printf("[sws] [sws] %p %p %p %p %p\n", spBrowser, lhwnd, GetWindowLongPtrW(FindWindowW(L"Progman", NULL), 0), FindWindowW(L"Progman", NULL), GetDesktopWindow());
					PDWORD_PTR res1 = -1, res2 = -1, res3 = -1;
					SendMessageTimeoutW(lhwnd, 0x052C, 0x0d, 0, SMTO_NORMAL, 1000, &res1);
					SendMessageTimeoutW(lhwnd, 0x052C, 0x0d, 1, SMTO_NORMAL, 1000, &res2);
					SendMessageTimeoutW(lhwnd, 0x052C, 0, 0, SMTO_NORMAL, 1000, &res3);
					bOk = !res1 && !res2 && !res3;
					spBrowser->lpVtbl->Release(spBrowser);
				}
				spdisp2->lpVtbl->Release(spdisp2);
			}
			spdisp->lpVtbl->Release(spdisp);
		}
		spShellWindows->lpVtbl->Release(spShellWindows);
	}
	return bOk;
}
```

**Comment by jdp1024** [comment]
`FindWindowW(L"Progman", NULL)` never fails on my computers. I don't know why.

According to [MS documentation](https://docs.microsoft.com/en-us/windows/win32/api/exdisp/nf-exdisp-ishellwindows-findwindowsw), there is still a chance that `IShellWindows::FindWindowSW` fails (by returning `S_FALSE`). I guess a sleep and retry loop may be necessary.

BTW, `USER32` also exports `GetShellWindow` and it is [documented](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getshellwindow).

**Comment by valinet** [comment]
> `FindWindowW(L"Progman", NULL)` never fails on my computers. I don't know why.

Yeah, who knows...

> According to [MS documentation](https://docs.microsoft.com/en-us/windows/win32/api/exdisp/nf-exdisp-ishellwindows-findwindowsw), there is still a chance that `IShellWindows::FindWindowSW` fails (by returning `S_FALSE`). I guess a sleep and retry loop may be necessary.

There is indeed a loop when calling the above, with a much shorter sleep.

> BTW, `USER32` also exports `GetShellWindow` and it is [documented](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getshellwindow).

Yeah, forgot about that. I have been running with the solution I posted about today all day, experienced no crash related to this. Seems to be pretty stable. `GetShellWindow` returns the same "progman" window, yet idk if it returns it after the window properly initialized itself. Probably it does, similar to how `IShellWindows::FindWindowSW` above seems. They are probably equivalent. Idk, I am actually a bit afraid to change it now, seems I hit the golden model.

I will soon push it as an update, that and hopefully the next stable version can drop sooner than later.

**Comment by jdp1024** [comment]
You can have a look into `CDesktopBrowser::_OnWallpaperUpdate` which is called by `CDesktopBrowser::_WndProcBS`, there is something interesting.

If `wParam` is 10 or 11 and msg is `0x52c`, `CDesktopBrowser::_IsDesktopWallpaperInitialized` is called and `0x80004005` will be returned if `_IsDesktopWallpaperInitialized` returns `FALSE`.

**Comment by valinet** [comment]
Yeah, true, missed that. It's right in front of my eyes. I hate when I overthink stuff too much. Thank you!

**Comment by valinet** [comment]
So something like this ought to be enough:

```
BOOL sws_WindowHelpers_EnsureWallpaperHWND()
{
        // See: https://github.com/valinet/ExplorerPatcher/issues/525
	HWND progman = GetShellWindow();
	if (progman)
	{
		PDWORD_PTR res0 = -1, res1 = -1, res2 = -1, res3 = -1;
		// Generate desktop wallpaper
		SendMessageTimeoutW(progman, 0x052C, 10, 0, SMTO_NORMAL, 1000, &res0);
		if (FAILED(res0))
		{
			return FALSE;
		}
		// Prepare to generate wallpaper window
		SendMessageTimeoutW(progman, 0x052C, 13, 0, SMTO_NORMAL, 1000, &res1);
		SendMessageTimeoutW(progman, 0x052C, 13, 1, SMTO_NORMAL, 1000, &res2);
		// "Animate desktop", which will make sure the wallpaper window is there
		SendMessageTimeoutW(progman, 0x052C, 0, 0, SMTO_NORMAL, 1000, &res3);
		//printf("[sws] Wallpaper results: %d %d %d\n", res1, res2, res3);		
		return !res1 && !res2 && !res3;
	}
	return FALSE;
}
```

**Comment by voomdoon** [comment]
is this problem back?
having `Windows Feature Experience Pack 1000.22659.1000.0` since yesterday, maybe KB5029263 is the cause?
